### ISSUE TITLE
In v1.0.9, can't manual added a PropTypes, the plugin will carash !!!

### ISSUE THREAD

**Issue by dpzxsm** [dpzxsm/ReactPropTypes-Plugin#5]
I found a bug when you manual added a PropTypes , will throw a error
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.HashMap
	at com.suming.plugin.ui.PropTypesModel.data2PropList(PropTypesModel.java:68)
	at com.suming.plugin.ui.PropTypesDialog.onOK(PropTypesDialog.java:177)
	at com.suming.plugin.ui.PropTypesDialog.lambda$new$0(PropTypesDialog.java:47)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)

**Comment by dpzxsm** [comment]
I'll fix it right away.
